version: "1.0"
environment: "production"
updated_at: "2025-01-15T10:30:00Z"
description: "TuneIn CDN benchmark broadcast groups - production streams"

broadcast_groups:
  newsfree:
    name: "O&O Talk"
    description: "O&O live talk and news broadcasts"
    content_type: "news"
    enabled: false
    broadcasts:
      msnbcfree:
        name: "MSNBC Free"
        description: "MSNBC live news broadcast for CDN latency testing"
        content_type: "news"
        enabled: true
        streams:
          pri_source:
            url: "https://tni-drct-msnbc-int-jg89w.fast.nbcuni.com/live/master.m3u8"
            type: "hls"
            role: "source"
            content_type: "news"
            enabled: true

          bk_source:
            url: "http://stream1.skyviewnetworks.com:8010/MSNBC"
            type: "icecast"
            role: "source"
            content_type: "news"
            enabled: true

          ti_hls:
            url: "https://hls.tunein.com/v3/newsfree/msnbcfree/master.m3u8"
            type: "hls"
            role: "cdn"
            content_type: "news"
            enabled: true

          ti_mp3:
            url: "https://cdn.tunein.com/v1/broadcast/newsfree/msnbcfree/stream.mp3"
            type: "icecast"
            role: "cdn"
            content_type: "news"
            enabled: true

          ss_ais_hls:
            url: "https://tunein.cdnstream1.com/3511_96.aac/playlist.m3u8"
            type: "hls"
            role: "cdn"
            content_type: "news"
            enabled: true

          ss_ais_mp3:
            url: "https://tunein.cdnstream1.com/3511_96.mp3"
            type: "icecast"
            role: "cdn"
            content_type: "news"
            enabled: true

      cnbcfree:
        name: CNBC Free
        enabled: true
        content_type: "news"
        streams:
          pri_source:
            url: "https://tni-drct-cnbc-wrld-ng93a.fast.nbcuni.com/live/master.m3u8"
            role: "source"
            enabled: true
          bk_source:
            url: "http://stream1.skyviewnetworks.com:8010/CNBC"
            role: "source"
            enabled: true
          ti_hls:
            url: "https://hls.tunein.com/v3/newsfree/msnbcfree/master.m3u8"
            role: "cdn"
            enabled: true
          ti_mp3:
            url: "http://cdn.tunein.com/v1/broadcast/newsfree/msnbcfree/stream.mp3"
            role: "cdn"
            enabled: true
          ss_ais_hls:
            url: "https://tunein.cdnstream1.com/3511_96.aac/playlist.m3u8"
            role: "cdn"
            enabled: true
          ss_ais_mp3:
            url: "https://tunein.cdnstream1.com/3511_96.mp3"
            role: "cdn"
            enabled: true

      cnnfree:
        name: "CNN"
        content_type: "news"
        enabled: false
        streams:
          pri_source:
            url: "https://turner-live-aka.cdn.turner.com/hls/live/2040557/cnnaudioonly/AUDIO_1_128000_eng.m3u8"
            role: "source"
            enabled: true
          bk_source:
            url: "http://stream1.skyviewnetworks.com:8010/CNN"
            role: "source"
            enabled: true
          ti_hls:
            url: "https://hls.tunein.com/v3/newsfree/msnbcfree/master.m3u8"
            role: "cdn"
            enabled: true
          ti_mp3:
            url: "http://cdn.tunein.com/v1/broadcast/newsfree/msnbcfree/stream.mp3"
            role: "cdn"
            enabled: true
          ss_ais_hls:
            url: "https://tunein.cdnstream1.com/3511_96.aac/playlist.m3u8"
            role: "cdn"
            enabled: true
          ss_ais_mp3:
            url: "https://tunein.cdnstream1.com/3511_96.mp3"
            role: "cdn"
            enabled: true

      foxfree:
        name: "Fox News"
        enabled: false
        streams:
          pri_source:
            url: "https://188a2110c0c0aa3d.mediapackage.us-east-2.amazonaws.com/out/v1/67fcd733de1c4728ac189e5dec958a18/master_1_0.m3u8"
            role: "source"
            enabled: true
          bk_source:
            url: "http://stream1.skyviewnetworks.com:8010/FOX"
            role: "source"
            enabled: true
          ti_hls:
            url: "https://hls.tunein.com/v3/newsfree/msnbcfree/master.m3u8"
            role: "cdn"
            enabled: true
          ti_mp3:
            url: "http://cdn.tunein.com/v1/broadcast/newsfree/msnbcfree/stream.mp3"
            role: "cdn"
            enabled: true
          ss_ais_hls:
            url: "https://tunein.cdnstream1.com/3511_96.aac/playlist.m3u8"
            role: "cdn"
            enabled: true
          ss_ais_mp3:
            url: "https://tunein.cdnstream1.com/3511_96.mp3"
            role: "cdn"
            enabled: true

      bloombergfree:
        name: "Bloomberg Free"
        enabled: false
        streams:
          pri_source:
            url: "https://drsf4spw8el1i.cloudfront.net/rad/Channel-RAD-AWS-virginia-1/Source-RadBBR-96-1_live.m3u8"
            role: "source"
            enabled: true
          bk_source:
            url: "https://d2r83kn0fbyxcp.cloudfront.net/rad/Channel-RAD-AWS-oregon-1/Source-RadBBR-96-2_live.m3u8"
            role: "source"
            enabled: true
          ti_hls:
            url: "https://hls.tunein.com/v3/newsfree/msnbcfree/master.m3u8"
            role: "cdn"
            enabled: true
          ti_mp3:
            url: "http://cdn.tunein.com/v1/broadcast/newsfree/msnbcfree/stream.mp3"
            role: "cdn"
            enabled: true
          ss_ais_hls:
            url: "https://tunein.cdnstream1.com/3511_96.aac/playlist.m3u8"
            role: "cdn"
            enabled: true
          ss_ais_mp3:
            url: "https://tunein.cdnstream1.com/3511_96.mp3"
            role: "cdn"
            enabled: true

      espnfree:
        name: "ESPN Free"
        enabled: false
        streams:
          pri_source:
            url: "https://ti.radio-prod.sportsradiocenter.com/ESPN/128k/program.m3u8"
            role: "source"
            enabled: true
          bk_source:
            url: "http://stream1.skyviewnetworks.com:8010/ESPN"
            role: "source"
            enabled: true
          ti_hls:
            url: "https://hls.tunein.com/v3/newsfree/msnbcfree/master.m3u8"
            role: "cdn"
            enabled: true
          ti_mp3:
            url: "http://cdn.tunein.com/v1/broadcast/newsfree/msnbcfree/stream.mp3"
            role: "cdn"
            enabled: true
          ss_ais_hls:
            url: "https://tunein.cdnstream1.com/3511_96.aac/playlist.m3u8"
            role: "cdn"
            enabled: true
          ss_ais_mp3:
            url: "https://tunein.cdnstream1.com/3511_96.mp3"
            role: "cdn"
            enabled: true

      skynewsfree:
        name: "Sky News Free"
        enabled: false
        streams:
          pri_source:
            url: "https://linear-uk-hls1-prod-main.cloudfront.skycdn.it/OFF/159218/radiotunein/master_mobile.m3u8?x-tunein-headers=x-cdnAuth:VUtjZG5UMFBTTnByMGRDbDB1ZEZyMG50aDNhZDNyUGE1NQ=="
            role: "source"
            enabled: true
          ti_hls:
            url: "https://hls.tunein.com/v3/newsfree/skynewsfree/master.m3u8"
            role: "cdn"
            enabled: true
          ti_mp3:
            url: "http://cdn.tunein.com/v1/broadcast/newsfree/skynewsfree/stream.mp3"
            role: "cdn"
            enabled: true
          ss_ais_hls:
            url: "https://tunein.cdnstream1.com/3511_96.aac/playlist.m3u8"
            role: "cdn"
            enabled: true
          ss_ais_mp3:
            url: "https://tunein.cdnstream1.com/3511_96.mp3"
            role: "cdn"
            enabled: true
