# Application settings
verbose: true
log_level: info
output_format: json

# Test configuration
test:
  timeout: 5m
  retry_attempts: 3
  retry_delay: 10s
  concurrent: true
  max_concurrency: 8

# Stream handling (global defaults)
stream:
  connection_timeout: 15s
  read_timeout: 60s
  buffer_size: 16384
  max_redirects: 5
  user_agent: "TuneIn-CDN-Benchmark-Prod/1.0"
  headers:
    "X-Forwarded-For": "10.0.0.1"
    "Cache-Control": "no-cache"
    "Accept-Encoding": "gzip, deflate"

# Audio processing (high quality)
audio:
  sample_rate: 48000
  channels: 2
  buffer_duration: 2s
  window_size: 4096
  overlap: 0.75
  window_function: "hamming"
  fft_size: 4096
  mel_bins: 256

# Quality thresholds
quality:
  min_similarity: 0.95
  max_latency: 2s
  min_bitrate: 256
  max_dropouts: 1
  buffer_health: 0.95

# Output configuration
output:
  precision: 4
  include_metadata: true
  timestamps: true
  colors: true
  pager: false

# HLS-specific configuration
hls:
  # Parser configuration
  parser:
    strict_mode: false
    max_segment_analysis: 15
    ignore_unknown_tags: false
    validate_uris: true
    custom_tag_handlers:
      "EXT-X-CUSTOM-TAG": "custom_handler"
      "EXT-X-TUNEIN-METADATA": "tunein_metadata_handler"

  # Metadata extraction configuration
  metadata_extractor:
    enable_url_patterns: true
    enable_header_mappings: true
    enable_segment_analysis: true
    default_values:
      codec: "aac"
      channels: 2
      sample_rate: 48000
      bitrate: 320

  # Stream detection configuration
  detection:
    url_patterns:
      - '\.m3u8$'
      - '/playlist\.m3u8'
      - '/master\.m3u8'
      - '/index\.m3u8'
      - '/live\.m3u8'
      - '/tunein\.m3u8'
    content_types:
      - "application/vnd.apple.mpegurl"
      - "application/x-mpegurl"
      - "vnd.apple.mpegurl"
      - "audio/mpegurl"
    required_headers: []
    timeout_seconds: 10

  # HTTP configuration for HLS requests
  http:
    user_agent: "TuneIn-CDN-Benchmark-HLS/2.0"
    accept_header: "application/vnd.apple.mpegurl,application/x-mpegurl,text/plain,*/*"
    connection_timeout: 10s
    read_timeout: 30s
    max_redirects: 3
    buffer_size: 32768
    custom_headers:
      "X-HLS-Client": "TuneIn-Benchmark"
      "X-Playback-Session-Id": "benchmark-session"

  # Audio-specific HLS configuration
  audio:
    sample_duration: 45s
    buffer_duration: 3s
    max_segments: 20
    follow_live: true
    analyze_segments: true

# ICEcast-specific configuration (placeholder)
icecast:
  # TODO: Future ICEcast configs will go here

# Regional configuration
regions:
  us-west-1:
    name: "US West (California)"
    endpoint: "https://us-west-1.tunein.com"
    location: "San Francisco, CA"
    enabled: true
    headers:
      "X-Region": "us-west-1"
      "X-CDN-Pop": "sfo"

  us-east-1:
    name: "US East (Virginia)"
    endpoint: "https://us-east-1.tunein.com"
    location: "Ashburn, VA"
    enabled: true
    headers:
      "X-Region": "us-east-1"
      "X-CDN-Pop": "iad"

  eu-west-1:
    name: "EU West (Ireland)"
    endpoint: "https://eu-west-1.tunein.com"
    location: "Dublin, Ireland"
    enabled: true
    headers:
      "X-Region": "eu-west-1"
      "X-CDN-Pop": "dub"

  ap-southeast-1:
    name: "Asia Pacific (Singapore)"
    endpoint: "https://ap-southeast-1.tunein.com"
    location: "Singapore"
    enabled: true
    headers:
      "X-Region": "ap-southeast-1"
      "X-CDN-Pop": "sin"

# Test profiles
profiles:
  development:
    name: "Development Testing"
    description: "Quick development testing with relaxed thresholds"
    duration: 2m
    regions: ["us-west-1"]
    metrics: ["latency", "quality"]
    streams:
      - name: "Dev HLS Stream"
        url: "https://dev.tunein.com/hls/test.m3u8"
        type: "hls"
        expected:
          bitrate: 128
          sample_rate: 44100
          channels: 2
          codec: "aac"
    thresholds:
      min_similarity: 0.85
      max_latency: 5s
      min_bitrate: 96
    tags:
      environment: "development"
      team: "engineering"

  production:
    name: "Production Benchmark"
    description: "Comprehensive production testing suite"
    duration: 10m
    regions: ["us-west-1", "us-east-1", "eu-west-1"]
    metrics: ["latency", "quality", "reliability", "spectral_analysis"]
    streams:
      - name: "Primary HLS Stream"
        url: "https://cdn1.tunein.com/hls/primary.m3u8"
        type: "hls"
        reference: "https://origin.tunein.com/hls/primary.m3u8"
        headers:
          "X-Test-Profile": "production"
        expected:
          bitrate: 320
          sample_rate: 48000
          channels: 2
          codec: "aac"
          format: "hls"

      - name: "Secondary HLS Stream"
        url: "https://cdn2.tunein.com/hls/secondary.m3u8"
        type: "hls"
        expected:
          bitrate: 256
          sample_rate: 44100
          channels: 2
          codec: "aac"

      - name: "Live News Stream"
        url: "https://live.tunein.com/news/bloomberg.m3u8"
        type: "hls"
        expected:
          bitrate: 192
          sample_rate: 44100
          channels: 2
          codec: "aac"

      - name: "Backup ICEcast Stream"
        url: "https://backup.tunein.com:8000/stream"
        type: "icecast"
        expected:
          bitrate: 192
          codec: "mp3"

    thresholds:
      min_similarity: 0.98
      max_latency: 1s
      min_bitrate: 256
      buffer_health: 0.95

    tags:
      environment: "production"
      team: "infrastructure"
      alert_channel: "cdn-alerts"
      priority: "high"

  stress_test:
    name: "Stress Testing"
    description: "High-load stress testing with many concurrent streams"
    duration: 30m
    regions: ["us-west-1", "us-east-1", "eu-west-1", "ap-southeast-1"]
    metrics: ["full_suite"]
    streams:
      - name: "Multiple HLS Variants"
        url: "https://stress.tunein.com/hls/multi-variant.m3u8"
        type: "hls"
        expected:
          bitrate: 320
          sample_rate: 48000
          channels: 2
    thresholds:
      min_similarity: 0.90
      max_latency: 3s
      min_bitrate: 128
      max_dropouts: 5
    tags:
      test_type: "stress"
      load_level: "high"
      automation: "true"

  nightly:
    name: "Nightly Regression"
    description: "Automated nightly testing across all regions"
    duration: 60m
    regions: ["us-west-1", "us-east-1", "eu-west-1", "ap-southeast-1"]
    metrics: ["full_suite", "performance_profiling"]
    streams:
      - name: "All Production Streams"
        url: "config://production_streams"
        type: "multiple"
      - name: "Edge Case Streams"
        url: "https://edge-cases.tunein.com/hls/problematic.m3u8"
        type: "hls"
        expected:
          bitrate: 64
          sample_rate: 22050
          channels: 1
    thresholds:
      min_similarity: 0.92
      max_latency: 2s
      min_bitrate: 64
      max_dropouts: 3
    tags:
      schedule: "nightly"
      automation: "true"
      coverage: "comprehensive"

  quick_check:
    name: "Quick Health Check"
    description: "Fast health check for CI/CD pipelines"
    duration: 30s
    regions: ["us-west-1"]
    metrics: ["basic_connectivity", "response_time"]
    streams:
      - name: "Health Check Stream"
        url: "https://health.tunein.com/hls/check.m3u8"
        type: "hls"
        expected:
          bitrate: 128
          codec: "aac"
    thresholds:
      max_latency: 1s
      min_bitrate: 96
    tags:
      type: "health_check"
      automation: "true"
      pipeline: "ci_cd"
