version: "1.0"
environment: "production"
updated_at: "2025-01-15T10:30:00Z"
description: "TuneIn CDN benchmark broadcast groups - production streams"

broadcast_groups:
  news_free:
    name: "O&O Talk"
    description: "O&O live talk and news broadcasts"
    content_type: "news"
    enabled: true
    broadcasts:
      cnbc_news_free:
        name: CNBC
        enabled: false
        content_type: "news"
        streams:
          pri_source:
            url: "http://hls.tunein.com/v3/newsfree/cnbcfree/master.m3u8"
            role: "source"
            enabled: true
          ti_mp3:
            url: "https://tunein.cdnstream1.com/3516_96.mp3"
            role: "cdn"
            enabled: true
          ss_ais_mp3:
            url: "https://tunein.cdnstream1.com/newsfree-cnbcfree"
            role: "cdn"
            enabled: true

      fox_news_free:
        name: "Fox News"
        enabled: false
        streams:
          pri_source:
            url: "http://hls.tunein.com/v3/newsfree/foxfree/master.m3u8"
            role: "source"
            enabled: true
          ti_mp3:
            url: "https://tunein.cdnstream1.com/2869_96.mp3"
            role: "cdn"
            enabled: true
          ss_ais_mp3:
            url: "https://tunein.cdnstream1.com/newsfree-foxfree"
            role: "cdn"
            enabled: true

      cnn_free:
        name: "CNN"
        content_type: "news"
        enabled: false
        streams:
          pri_source:
            url: "http://hls.tunein.com/v3/newsfree/cnnfree/master.m3u8"
            role: "source"
          ti_mp3:
            url: "https://tunein.cdnstream1.com/2868_96.mp3"
            role: "cdn"
          ss_ais_mp3:
            url: "https://tunein.cdnstream1.com/newsfree-cnnfree"
            role: "cdn"

      cnn_hln:
        name: "CNN HLN"
        content_type: "news"
        enabled: false
        streams:
          pri_source:
            url: "http://hls.tunein.com/v3/newsfree/cnnhln/master.m3u8"
            role: "source"
          ti_mp3:
            url: "https://tunein.cdnstream1.com/2876_96.mp3"
            role: "cdn"
          ss_ais_mp3:
            url: "https://tunein.cdnstream1.com/newsfree-cnnhln"
            role: "cdn"

      msnbc_news_free:
        name: "MSNBC News Free"
        description: "MSNBC live news broadcast for CDN latency testing"
        content_type: "news"
        enabled: true
        streams:
          pri_source:
            url: "https://tni-drct-msnbc-int-jg89w.fast.nbcuni.com/live/master.m3u8"
            type: "hls"
            role: "source"
            content_type: "news"
            enabled: true

          bk_source:
            url: "http://stream1.skyviewnetworks.com:8010/MSNBC"
            type: "icecast"
            role: "source"
            content_type: "news"
            enabled: true

          ti_hls:
            url: "https://hls.tunein.com/v3/newsfree/msnbcfree/master.m3u8"
            type: "hls"
            role: "cdn"
            content_type: "news"
            enabled: true

          ti_mp3:
            url: "https://cdn.tunein.com/v1/broadcast/newsfree/msnbcfree/stream.mp3"
            type: "icecast"
            role: "cdn"
            content_type: "news"
            enabled: true

          ss_ais_hls:
            url: "https://tunein.cdnstream1.com/3511_96.aac/playlist.m3u8"
            type: "hls"
            role: "cdn"
            content_type: "news"
            enabled: true

          ss_ais_mp3:
            url: "https://tunein.cdnstream1.com/3511_96.mp3"
            type: "icecast"
            role: "cdn"
            content_type: "news"
            enabled: true
